import type { CategorizedCommits, OutputOptions, SummaryStats } from "@/types";
import { calculateStats } from "./calculate-stats";
import { formatCommitLine } from "./format-commit";
import {
  generateCategoryFirstSections,
  generateRepoFirstSections,
  type SectionFormatter,
} from "./generate-sections";

/**
 * Creates a markdown section formatter
 * @param locale - Locale for date formatting
 * @param showBranches - Whether to show branch information
 * @returns SectionFormatter for markdown output
 */
const createMarkdownSectionFormatter = (
  locale: string,
  showBranches: boolean,
): SectionFormatter => ({
  level1Header: (name: string) => `## ${name}\n\n`,
  level2Header: (name: string) => `### ${name}\n\n`,
  commitLine: commit =>
    formatCommitLine(commit, {
      format: "markdown",
      locale,
      showBranches,
      isColorsEnabled: false,
    }),
  sectionSeparator: () => "---\n\n",
});

/**
 * Generates summary section
 * @param categorizedCommits - Commits grouped by category
 * @param dateRange - Optional date range
 * @returns Summary markdown string
 */
const generateSummary = (
  categorizedCommits: CategorizedCommits,
  dateRange?: { since: string; until: string },
): string => {
  const { totalCommits, repos } = calculateStats(categorizedCommits);

  let summary = "## Summary\n\n";
  summary += `- **Total Commits**: ${totalCommits.toString()}\n`;
  summary += `- **Repositories**: ${[...repos].join(", ")}\n`;

  if (dateRange) {
    summary += `- **Date Range**: ${dateRange.since} to ${dateRange.until}\n`;
  }

  return summary + "\n---\n\n";
};

/**
 * Generates summary section with branch information
 * @param stats - Summary statistics
 * @param dateRange - Optional date range
 * @returns Summary markdown string
 */
const generateSummaryWithBranches = (
  stats: SummaryStats,
  dateRange?: { since: string; until: string },
): string => {
  let summary = "## Summary\n\n";
  summary += `- **Total Commits**: ${stats.totalCommits.toString()}\n`;
  summary += `- **Merged to Main**: ${stats.mergedCommits.toString()}\n`;
  summary += `- **In Progress**: ${stats.unmergedCommits.toString()}\n`;
  summary += `- **Repositories**: ${[...stats.repos].join(", ")}\n`;

  if (dateRange) {
    summary += `- **Date Range**: ${dateRange.since} to ${dateRange.until}\n`;
  }

  return summary + "\n---\n\n";
};

/**
 * Generates markdown output with category-first grouping
 * @param categorizedCommits - Commits grouped by category
 * @param locale - Locale for date formatting
 * @param showBranches - Whether to show branch names
 * @returns Markdown string
 */
const generateCategoryFirst = (
  categorizedCommits: CategorizedCommits,
  locale: string,
  showBranches = false,
): string => {
  const formatter = createMarkdownSectionFormatter(locale, showBranches);
  return generateCategoryFirstSections(categorizedCommits, formatter);
};

/**
 * Generates markdown output with repo-first grouping
 * @param categorizedCommits - Commits grouped by category
 * @param locale - Locale for date formatting
 * @param showBranches - Whether to show branch names
 * @returns Markdown string
 */
const generateRepoFirst = (
  categorizedCommits: CategorizedCommits,
  locale: string,
  showBranches = false,
): string => {
  const formatter = createMarkdownSectionFormatter(locale, showBranches);
  return generateRepoFirstSections(categorizedCommits, formatter);
};

/**
 * Generates markdown output for categorized commits
 * @param categorizedCommits - Commits grouped by category
 * @param options - Output configuration options
 * @param dateRange - Optional date range for summary
 * @returns Formatted markdown string
 */
export const generateMarkdownOutput = (
  categorizedCommits: CategorizedCommits,
  options: OutputOptions,
  dateRange?: { since: string; until: string },
): string => {
  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  let output = `# Dev Log: ${today}\n\n`;

  if (options.showSummary) {
    output += generateSummary(categorizedCommits, dateRange);
  }

  output +=
    options.groupBy === "repo"
      ? generateRepoFirst(categorizedCommits, options.locale)
      : generateCategoryFirst(categorizedCommits, options.locale);

  output += "_Generated by devrec_\n";

  return output;
};

/**
 * Generates markdown output with branch information
 * @param merged - Merged commits grouped by category
 * @param unmerged - Unmerged commits grouped by category
 * @param stats - Summary statistics
 * @param options - Output configuration options
 * @param dateRange - Optional date range for summary
 * @returns Formatted markdown string
 */
export const generateMarkdownOutputWithBranches = (
  merged: CategorizedCommits,
  unmerged: CategorizedCommits,
  stats: SummaryStats,
  options: OutputOptions,
  dateRange?: { since: string; until: string },
): string => {
  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  let output = `# Dev Log: ${today}\n\n`;

  if (options.showSummary) {
    output += generateSummaryWithBranches(stats, dateRange);
  }

  if (stats.mergedCommits > 0) {
    output += "## Merged Work\n\n";
    output +=
      options.groupBy === "repo"
        ? generateRepoFirst(merged, options.locale, false)
        : generateCategoryFirst(merged, options.locale, false);
  }

  if (stats.unmergedCommits > 0) {
    output += "## In Progress (Unmerged)\n\n";
    output +=
      options.groupBy === "repo"
        ? generateRepoFirst(unmerged, options.locale, true)
        : generateCategoryFirst(unmerged, options.locale, true);
  }

  output += "_Generated by devrec_\n";

  return output;
};
